dj_millionaires_service/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls', namespace='core')),
    path('search/', include('search.urls', namespace='search')),
    path('users/', include('users.urls', namespace='users')),
    path('__debug__/', include('debug_toolbar.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dj_millionaires_service/core/urls.py
from django.urls import path
from core.constants import TOP_MILLIONAIRES_COUNT
from core.views import (millionaire_list_view, millionaire_vote_create_view,
                        top_millionaires_index_view,)

app_name = 'core'
urlpatterns = [
    path('', millionaire_list_view, name='millionaire_list_url'),
    path(f'top{TOP_MILLIONAIRES_COUNT}/', top_millionaires_index_view, 
        name='top_millionaires_index_url'),
    path('vote/<int:millionaire_id>/', millionaire_vote_create_view, 
        name='millionaire_vote_create_url'),
]

dj_millionaires_service/core/models/information_models.py
from django.db import models


class Country(models.Model):
    name = models.CharField(max_length=255, unique=True, db_index=True)
    population = models.IntegerField(null=True, blank=True)
    flag = models.ImageField(upload_to='country_flags/', null=True, blank=True)

    class Meta:
        indexes = [
            models.Index(fields=['name',]),
        ]

    def __str__(self) -> str:
        return self.name


class Company(models.Model):
    name = models.CharField(max_length=255, db_index=True)
    country = models.ForeignKey(Country, on_delete=models.CASCADE, related_name='companies')
    number_of_employees = models.IntegerField(null=True, blank=True)
    net_worth = models.IntegerField(null=True, blank=True)

    class Meta:
        indexes = [
            models.Index(fields=['name',]),
        ]

    def __str__(self) -> str:
        return self.name

dj_millionaires_service/core/models/millionaire_models.py
from email.policy import default
from django.db import models
from django.contrib.postgres.search import SearchVectorField
from django.contrib.postgres.indexes import GinIndex

from core.models.information_models import Company, Country


class Millionaire(models.Model):
    name = models.CharField(max_length=255)
    image = models.ImageField(upload_to='profile_pics/', default='system_default.png')
    country = models.ForeignKey(Country, on_delete=models.CASCADE, related_name='millionaires')
    city = models.CharField(max_length=255)
    address = models.CharField(max_length=255)
    company = models.ForeignKey(Company, on_delete=models.CASCADE, related_name='millionaires')
    profession = models.CharField(max_length=255)
    phone = models.CharField(max_length=255)
    # https://pganalyze.com/blog/full-text-search-django-postgres
    vector_column = SearchVectorField(null=True)

    class Meta:
        db_table = u'millionaire'
        indexes = [
            GinIndex(fields=['vector_column']),
            models.Index(fields=['name', 'profession',]),
        ]


    def __str__(self):
        return self.name

dj_millionaires_service/core/models/voting_models.py
from django.db import models
from core.models.millionaire_models import Millionaire
from system.models import BaseModel


class VoteMillionaire(BaseModel):
    millionaire = models.ForeignKey(Millionaire, on_delete=models.CASCADE, related_name='votes')

    def __str__(self) -> str:
        votes= self.millionaire.votes.count()
        return f"{self.millionaire.name} {votes}"

dj_millionaires_service/core/views.py
from django.db.models import Count
from django.shortcuts import redirect
from django.views.generic import ListView, View
from core.constants import TOP_MILLIONAIRES_COUNT
from core.models import Millionaire, VoteMillionaire


class MillionaireListView(ListView):
    model = Millionaire
    paginate_by = 16
    template_name = 'core/index.html'

    def get_queryset(self):
        return self.model.objects.prefetch_related('country', 'company', 'votes')


millionaire_list_view = MillionaireListView.as_view()


class MillionaireVoteCreateView(View):
    def get(self, request, millionaire_id, *args, **kwargs):
        VoteMillionaire.objects.create(millionaire_id=millionaire_id)
        return redirect('core:millionaire_list_url')


millionaire_vote_create_view = MillionaireVoteCreateView.as_view()


class TopMillionairesIndexView(ListView):
    model = Millionaire
    template_name = 'core/index.html'

    def get_queryset(self):
        top_millionaires = self.model.objects.prefetch_related('country', 'company', 'votes')\
            .annotate(votes_count=Count('votes')).order_by('-votes_count')[:TOP_MILLIONAIRES_COUNT]
        return top_millionaires[:TOP_MILLIONAIRES_COUNT]


top_millionaires_index_view = TopMillionairesIndexView.as_view()

dj_millionaires_service/core/templates/core/index.html
{% extends "base.html" %}
{% load pagination_tags %}
{% block title %}
    Home | {{ block.super }}
{% endblock %}

{% block body %}
<div class="container" id="millionaires-container">
    {% if query %}
        <div class="row mt-5">
            <div class="col">
                <small class="text-primary">
                    Showing results for <em><b>{{ query }} </b></em>
                    ({{ paginator.count }} records across {{ paginator.num_pages }} pages).
                </small>
            </div>
        </div>
    {% endif %}

    <div class="row justify-content-center mt-1">
        {% for object in object_list %}
            <div class="col-12 col-md-4 col-lg-3 col-xl-3 my-2">
                <div class="card">
                    {% if object.image %}
                        <img class="card-img-top" 
                            src="{{ object.image.url }}" 
                            alt="{{ object.name }}">
                    {% endif %}
                    <div class="card-body">
                        <h5 class="card-title">
                            {% if object.name_headline %}
                                {{ object.name_headline | safe }}
                            {% else %} 
                                {{ object.name }}
                            {% endif %}
                        </h5>
                        <p class="card-text">{{ object.address }}</p>
                        
                        <a class="" data-toggle="collapse" href="#collapseInformation{{ object.id }}" role="button" aria-expanded="false"
                            aria-controls="collapseExample">Info 👇👇👇
                        </a>
                    </div>
                    <div class="{% if not query %}collapse{% endif %}" id="collapseInformation{{ object.id }}">
                        <ul class="list-group list-group-flush">
                            <li class="list-group-item">
                                <strong>Country: </strong> {{ object.country }}
                            </li>
                            <li class="list-group-item">
                                <strong>City: </strong> {{ object.city }}
                            </li>
                            <li class="list-group-item">
                                <strong>Company: </strong> {{ object.company }}
                            </li>
                            <li class="list-group-item">
                                <strong>Profession: </strong> 
                                {% if object.profession_headline %}
                                    {{ object.profession_headline | safe }}
                                {% else %}
                                    {{ object.profession }}
                                {% endif %}
                            </li>
                            <li class="list-group-item">
                                <strong>Phone: </strong> {{ object.phone }}
                            </li>
                        </ul>
                    </div>
                    <div class="card-body d-flex justify-content-between p-1">
                        <a href="#" class="card-link">{{ object.votes.count }} Votes</a>
                        <a href="{% url 'core:millionaire_vote_create_url' object.id %}" class="card-link">👍</a>
                    </div>
                </div>
            </div>
        {% empty %}
        <div class="col-6">
            <h5>No Millionaire Records Found!</h5>
        </div>
        {% endfor %}
    </div>

    <!-- Pagination -->
    {% if is_paginated %}
    <div class="row justify-content-center mt-3">
        <nav hx-target="#main" hx-swap="outerHTML" hx-push-url="true">
            <ul class="pagination">
                {% if page_obj.number != 1 %}
                <li class="page-item">
                    <a class="page-link" hx-get="?{% url_replace request 'page' 1 %}" 
                        href="?{% url_replace request 'page' 1 %}">
                        &laquo; First
                    </a>
                </li>
                {% endif %}
                {% if page_obj.has_previous %}
                <li  class="page-item">
                    <a class="page-link" 
                        hx-get="?{% url_replace request 'page' page_obj.previous_page_number %}" 
                        href="?{% url_replace request 'page' page_obj.previous_page_number %}">
                        {{ page_obj.previous_page_number }}
                    </a>
                </li>
                {% endif %}
                <li class="page-item active">
                    <a class="page-link" href="?{% url_replace request 'page' page_obj.number %}">
                        {{ page_obj.number }}
                    </a>
                </li>
                {% if page_obj.has_next %}
                <li class="page-item">
                    <a class="page-link" hx-get="?{% url_replace request 'page' page_obj.next_page_number %}" 
                        href="?{% url_replace request 'page' page_obj.next_page_number %}">
                        {{ page_obj.next_page_number }}
                    </a>
                </li>
                {% endif %}
                {% if page_obj.number != page_obj.paginator.num_pages %}
                <li class="page-item">
                    <a class="page-link" hx-get="?{% url_replace request 'page' page_obj.paginator.num_pages %}"
                        href="?{% url_replace request 'page' page_obj.paginator.num_pages %}">
                        &raquo; Last
                    </a>
                </li>
                {% endif %}
            </ul>
        </nav>
    </div>
    {% endif %}
</div>
{% endblock %} 