dj_millionaires_service/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls', namespace='core')),
    path('search/', include('search.urls', namespace='search')),
    path('users/', include('users.urls', namespace='users')),
    path('__debug__/', include('debug_toolbar.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dj_millionaires_service/core/urls.py
from django.urls import path
from core.constants import TOP_MILLIONAIRES_COUNT
from core.views import (millionaire_list_view, millionaire_vote_create_view,
                        top_millionaires_index_view,)

app_name = 'core'
urlpatterns = [
    path('', millionaire_list_view, name='millionaire_list_url'),
    path(f'top{TOP_MILLIONAIRES_COUNT}/', top_millionaires_index_view, 
        name='top_millionaires_index_url'),
    path('vote/<int:millionaire_id>/', millionaire_vote_create_view, 
        name='millionaire_vote_create_url'),
]

dj_millionaires_service/search/urls.py
from django.urls import path
from search.views import search_view


app_name = 'search'
urlpatterns = [
    path('', search_view, name='search_url'),
]

dj_millionaires_service/users/urls.py
from django.urls import path

from users.views import registration_view, login_view, logout_view


app_name = 'users'
urlpatterns = [
    path('registration/', registration_view, name='registration_url'),
    path('login/', login_view, name='login_url'),
    path('logout/', logout_view, name='logout_url'),
]

dj_millionaires_service/templates/_partials/_messages.html
{% if messages %}
    {% for message in messages %}
        <li><strong class="text-danger">Error: </strong> {{ message }}</li>
    {% endfor %}
{% endif %}

dj_millionaires_service/templates/_partials/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container">
        <a class="navbar-brand" href="#">Millionaire's Club</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02"
            aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        
        <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
            <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
                <li class="nav-item 
                    {% if request.resolver_match.url_name == 'millionaire_list_url' %} active {% endif %}">
                    <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item {% if request.resolver_match.url_name == 'top_millionaires_index_url' %} active {% endif %}">
                    <a class="nav-link" href="{% url 'core:top_millionaires_index_url' %}">
                        # Top {{ top_millionaires_count }} 👑
                    </a>
                </li>
            </ul>
            <form class="form-inline my-2 my-lg-0 justify-content-md-end" method="GET" 
                action="{% url 'search:search_url' %}" style="flex-grow: 1;">
                <input class="form-control mr-sm-2" type="search" 
                    placeholder="Search" name="q" value="{% if query %}{{ query }}{% endif %}"
                    style="width: 70%;">
                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
            </form>
            {% if request.user.is_authenticated %}
                <a href="{% url 'users:logout_url' %}" class="btn btn-success ml-2">
                    Logout {{ user.user_profile }}
                </a>
            {% else %}
                <a href="{% url 'users:registration_url' %}" class="btn btn-success ml-2">
                    Join
                </a>
            {% endif %}
        </div>
    </div>
</nav>